name: augur
description: "A flutter project for the User Interface of the AUSPEX Framework."
publish_to: 'none'
version: 0.9.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^8.0.1
  url_launcher: ^6.3.0
  latlong2: ^0.9.1
  http: ^1.2.1
  material_symbols_icons: ^4.2762.0
  geolocator: ^14.0.2
  roslibdart: ^0.0.1-dev+4
  vector_math: ^2.1.4
  flutter_launcher_icons: ^0.14.1
  redis: ^4.0.0
  flutter_riverpod: ^2.6.1
  permission_handler: ^12.0.1
  sherpa_onnx: ^1.10.46
  sherpa_onnx_linux: ^1.10.46
  sherpa_onnx_android: ^1.10.46
  sherpa_onnx_windows: ^1.10.46
  record: ^6.1.0
  path_provider: ^2.1.5
  path: ^1.9.0
  audioplayers: ^6.4.0
  asset_fill: ^2.0.0
  rational: ^2.2.3
  media_kit: ^1.2.1
  media_kit_video: ^1.2.2
  media_kit_libs_video: ^1.0.5


# dependency_overrides:
#   http: ^1.2.0
#   record_linux: 0.7.2
#   record_platform_interface: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/augur_icon.png"
  adaptive_icon_foreground: "assets/icons/augur_icon.png"
  adaptive_icon_background: "#ffffff"  # Change to a solid color or a valid image path
  min_sdk_android: 26
  windows:
    generate: true
    image_path: "assets/icons/augur_icon.png"
    icon_size: 256 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/models/
    - assets/models/asr/
    - assets/models/tts/
    - assets/models/tts/espeak-ng-data/
    - assets/models/tts/espeak-ng-data/lang/
    - assets/models/tts/espeak-ng-data/lang/aav/
    - assets/models/tts/espeak-ng-data/lang/art/
    - assets/models/tts/espeak-ng-data/lang/azc/
    - assets/models/tts/espeak-ng-data/lang/bat/
    - assets/models/tts/espeak-ng-data/lang/bnt/
    - assets/models/tts/espeak-ng-data/lang/ccs/
    - assets/models/tts/espeak-ng-data/lang/cel/
    - assets/models/tts/espeak-ng-data/lang/cus/
    - assets/models/tts/espeak-ng-data/lang/dra/
    - assets/models/tts/espeak-ng-data/lang/esx/
    - assets/models/tts/espeak-ng-data/lang/gmq/
    - assets/models/tts/espeak-ng-data/lang/gmw/
    - assets/models/tts/espeak-ng-data/lang/grk/
    - assets/models/tts/espeak-ng-data/lang/inc/
    - assets/models/tts/espeak-ng-data/lang/ine/
    - assets/models/tts/espeak-ng-data/lang/ira/
    - assets/models/tts/espeak-ng-data/lang/iro/
    - assets/models/tts/espeak-ng-data/lang/itc/
    - assets/models/tts/espeak-ng-data/lang/jpx/
    - assets/models/tts/espeak-ng-data/lang/map/
    - assets/models/tts/espeak-ng-data/lang/miz/
    - assets/models/tts/espeak-ng-data/lang/myn/
    - assets/models/tts/espeak-ng-data/lang/poz/
    - assets/models/tts/espeak-ng-data/lang/roa/
    - assets/models/tts/espeak-ng-data/lang/sai/
    - assets/models/tts/espeak-ng-data/lang/sem/
    - assets/models/tts/espeak-ng-data/lang/sit/
    - assets/models/tts/espeak-ng-data/lang/tai/
    - assets/models/tts/espeak-ng-data/lang/trk/
    - assets/models/tts/espeak-ng-data/lang/urj/
    - assets/models/tts/espeak-ng-data/lang/zle/
    - assets/models/tts/espeak-ng-data/lang/zls/
    - assets/models/tts/espeak-ng-data/lang/zlw/
    - assets/models/tts/espeak-ng-data/voices/
    - assets/models/tts/espeak-ng-data/voices/!v/

